### ISSUE TITLE
想了解下, 为什么感觉上首页列表滑动起来有些卡顿?  

### ISSUE THREAD

**Issue by shaopx** [wangchenyan/wanandroid-compose#2]
是compose本身的性能缺陷吗?  还是实现上可能不够完美?  
求大神回复

**Comment by wangchenyan** [comment]
目前应该都是按照官方示例实现的，个人感觉 compose 目前还是无法达到原生的性能，这篇文章中也有测试 https://juejin.cn/post/7008522702835154980

**Comment by shaopx** [comment]
谢谢大佬
